FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY nearby.html /usr/share/nginx/html/nearby.html
COPY app.js /usr/share/nginx/html/app.js
COPY nearby.js /usr/share/nginx/html/nearby.js
COPY style.css /usr/share/nginx/html/style.css

EXPOSE 80

