

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ess_data:/data
    env_file:
      - .env
    environment:
      - EVE_CLIENT_ID
      - EVE_CLIENT_SECRET
      - EVE_CALLBACK_URL
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  ess_data:

